### ISSUE TITLE
多类分割问题

### ISSUE THREAD

**Issue by yuyunlong2002** [920232796/SETR-pytorch#10]
您好，看完了您的车辆分割代码，想请问一下如果分割的目标有多类（比如说不只有车，还有行人，树，道路等等），应该如何来更改代码呢？

**Comment by rongtongxueya** [comment]
遇到了相同的问题，请问您现在解决了吗，可以给出一点点思路吗

**Comment by zhouweirui** [comment]
可以在最后一层卷积输出通道数为类别数，outchanel=num_classes，然后在计算loss的时候用交叉熵（我二分类用交叉熵还挺好用），预测的时候用argmax再映射成不同颜色
